### ISSUE TITLE
Extending IdentityUser

### ISSUE THREAD

**Issue by TDK1964-1** [JonPSmith/PermissionsOnlyApp#1]
Hi Jon, 

How would I extend your implementation to add additional fields to IdentityUser?

Thanks, Tim

**Comment by JonPSmith** [comment]
That's an ASP.NET Core issue - see [this link](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-3.1#customize-the-model) on how to do that.
